/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.config;

import Controlador.ControladorConfigurarAreas;
import Controlador.Interfaces.VistaConfigurarAreas;
import Modelo.Datos.Area;
import Modelo.Logica.SistemaAreas;
import Vista.atencion.SolicitudNumero;

import java.util.List;


public class ConfigurarAreas extends javax.swing.JFrame implements VistaConfigurarAreas{

    //Atributos
    private Area area;
    private SistemaAreas sa;
    private ControladorConfigurarAreas controlador;
    
    //Accesores y modificadores
    public Area getArea() {
        return area;
    }

    public void setArea(Area area) {
        this.area = area;
    }

    public SistemaAreas getSa() {
        return sa;
    }

    public void setSa(SistemaAreas sa) {
        this.sa = sa;
    }

    public ControladorConfigurarAreas getControlador() {
        return controlador;
    }

    public void setControlador(ControladorConfigurarAreas controlador) {
        this.controlador = controlador;
    }
 
    
    //Constructores
    public ConfigurarAreas() {
        initComponents();
        controlador = new ControladorConfigurarAreas(this);
        cargarAreas();//muestra en  campo de area
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstAreas = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(lstAreas);

        jLabel1.setText("CONFIGURAR AREAS");

        jLabel2.setText("Lista de áreas:");

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnSeleccionar)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnSeleccionar)))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        Area areaSeleccionada = (Area) lstAreas.getSelectedValue();
        abrirSolicitudNumero(areaSeleccionada);
        
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstAreas;
    // End of variables declaration//GEN-END:variables

    //Métodos----------------------------------------------------------------
    
    public void cargarAreas() {
        controlador.obtenerAreas(area);
    }

    @Override
    public void cargarAreas(List<Area> area) {
        lstAreas.setListData(area.toArray());
    }
   
   //------------------------------------------------------------------
    @Override
    public void abrirSolicitudNumero(Area a) {
        dispose();
        new SolicitudNumero(a).setVisible(true);
    }

    
  //--------------------------------------------------------------------------  
}
