/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.atencion;

import Controlador.ControladorAtencionTrabajador;
import Controlador.Interfaces.VistaAtencionTrabajador;
import Modelo.Datos.Atencion;
import Modelo.Datos.Cliente;
import Modelo.Datos.Sector;
import Modelo.Sistema;
import Modelo.Datos.Trabajador;
import Modelo.Logica.SistemaAtenciones;

import java.text.SimpleDateFormat;

public class AtencionTrabajador extends javax.swing.JFrame implements VistaAtencionTrabajador {

    //Atributos
    private ControladorAtencionTrabajador controlador;
    private Trabajador trabajador;
    private Sector sector;
    private Atencion atencion;
    private Sistema sistema;
    private SistemaAtenciones sat;

    public Sector getSector() {
        return sector;
    }

    public void setSector(Sector sector) {
        this.sector = sector;
    }

    public Atencion getAtencion() {
        return atencion;
    }

    public void setAtencion(Atencion atencion) {
        this.atencion = atencion;
    }

    //Accesores y modificadores
    public ControladorAtencionTrabajador getControlador() {
        return controlador;
    }

    public void setControlador(ControladorAtencionTrabajador controlador) {
        this.controlador = controlador;
    }

    public Trabajador getTrabajador() {
        return trabajador;
    }

    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }

    public SistemaAtenciones getSat() {
        return sat;
    }

    public void setSat(SistemaAtenciones sat) {
        this.sat = sat;
    }

    //Constructor--------------------------------------------------
    public AtencionTrabajador(Trabajador trabajador) {
        initComponents();
        this.trabajador = trabajador;
        this.sistema = Sistema.getInstancia();
        controlador = new ControladorAtencionTrabajador(this);
        controlador.cargarAtencion();
        cargarEtiquetas(trabajador);
    }
    //---------------------------------------------------------------  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNombreTrabajador = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNumeroPuesto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombreArea = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAbrirAtencion = new javax.swing.JButton();
        btnFinAtencion = new javax.swing.JButton();
        btnDerivar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblNrosAsignados = new javax.swing.JLabel();
        lblNrosEspera = new javax.swing.JLabel();
        lblTiempoPromedio = new javax.swing.JLabel();
        lblSector = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        txtDatosAtencion = new javax.swing.JTextArea();
        lblDerivados = new javax.swing.JLabel();
        lblDatosAtencion = new javax.swing.JLabel();
        labelAsignados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre trabajador:");

        jLabel2.setText("Número puesto:");

        lblNumeroPuesto.setText("jLabel3");

        jLabel3.setText("Área:");

        lblNombreArea.setText("jLabel4");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ATENDER CLIENTES");

        jLabel5.setText("Sector:");

        btnAbrirAtencion.setText("Abrir Atención");
        btnAbrirAtencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirAtencionActionPerformed(evt);
            }
        });

        btnFinAtencion.setText("Finalizar Atención");

        btnDerivar.setText("Derivar Atención");

        BtnSalir.setText("Finalizar y Salir");

        jLabel6.setText("Números Asignados:");

        jLabel7.setText("Números Derivados en Espera:");

        jLabel8.setText("Tiempo Promedio:");

        lblSector.setText("sector");

        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        txtDescripcion.setEnabled(false);
        jScrollPane1.setViewportView(txtDescripcion);

        txtDatosAtencion.setColumns(20);
        txtDatosAtencion.setRows(5);
        txtDatosAtencion.setEnabled(true);
        jScrollPane2.setViewportView(txtDatosAtencion);

        lblDerivados.setText("lblDerivados");

        labelAsignados.setText("asignados");
        lblDatosAtencion.setText("Datos de Atencion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSector)
                                        .addComponent(lblNombreArea)
                                        .addComponent(lblNumeroPuesto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(4, 4, 4)
                                                .addComponent(lblNrosAsignados)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelAsignados))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(56, 56, 56)
                                                .addComponent(lblTiempoPromedio))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDerivados)))
                                .addGap(131, 131, 131)
                                .addComponent(lblNrosEspera)
                                .addGap(267, 267, 267))
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(39, 39, 39)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(btnAbrirAtencion)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnFinAtencion)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(btnDerivar)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(BtnSalir))
                                                        .addComponent(jScrollPane1)
                                                        .addComponent(jScrollPane2)
                                                ))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(142, 142, 142)
                                                .addComponent(lblNombreTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(lblNombreTrabajador)
                                        .addComponent(jLabel6)
                                        .addComponent(lblNrosAsignados)
                                        .addComponent(labelAsignados))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(lblNumeroPuesto)
                                        .addComponent(jLabel7)
                                        .addComponent(lblNrosEspera)
                                        .addComponent(lblDerivados))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(lblNombreArea)
                                        .addComponent(jLabel8)
                                        .addComponent(lblTiempoPromedio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(lblSector))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnAbrirAtencion)
                                        .addComponent(btnFinAtencion)
                                        .addComponent(btnDerivar)
                                        .addComponent(BtnSalir))
                                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirAtencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirAtencionActionPerformed
        txtDescripcion.enable(true);
        controlador.abrirAtencion(trabajador, atencion);

    }//GEN-LAST:event_btnAbrirAtencionActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton btnAbrirAtencion;
    private javax.swing.JButton btnDerivar;
    private javax.swing.JButton btnFinAtencion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAsignados;
    private javax.swing.JLabel lblDerivados;
    private javax.swing.JLabel lblNombreArea;
    private javax.swing.JLabel lblNombreTrabajador;
    private javax.swing.JLabel lblNrosAsignados;
    private javax.swing.JLabel lblNrosEspera;
    private javax.swing.JLabel lblNumeroPuesto;
    private javax.swing.JLabel lblSector;
    private javax.swing.JLabel lblTiempoPromedio;
    private javax.swing.JLabel lblDatosAtencion;
    private javax.swing.JTextArea txtDatosAtencion;
    private javax.swing.JTextArea txtDescripcion;
    // End of variables declaration//GEN-END:variables

    //Métodos
    @Override
    public void cargarEtiquetas(Trabajador trabajador) {
        this.trabajador = trabajador;
        lblNombreTrabajador.setText(this.trabajador.getNombreCompleto());
        int x = this.trabajador.devolverPuestoTrabajador().getNumPuesto();//devuelve un nro
        String texto = String.valueOf(x);//paso a sring el nro
        lblNumeroPuesto.setText(texto);//lo muestro en la etiqueta
        lblNombreArea.setText(this.trabajador.devolverNombreAreaSectorTrabajador());
        lblSector.setText(this.trabajador.devolverNombreSectorTrabajador());
        lblTiempoPromedio.setText(String.valueOf(this.trabajador.getTiempoPromedioAtencion()));
        labelAsignados.setText(String.valueOf(this.trabajador.getCantidadAtenciones()));
        lblDerivados.setText(String.valueOf(this.trabajador.getCantidadNumerosDerivados()));
    }

    @Override
    public void cargarAtencion(Atencion atencion, Cliente cliente) {
        if (atencion != null && cliente != null) {
            if (this.atencion == null) {
                this.atencion = atencion;
                String fechaSolicitud = new SimpleDateFormat("dd/MM/yyyy").format(this.atencion.getFechaSolicitudNumero());
                String horaSolicitud = new SimpleDateFormat("hh:mm").format(this.atencion.getFechaSolicitudNumero());
                String info = "*Información del Cliente \n _____________________" + "\n"
                        + "*Nombre Cliente:" + cliente.getNombreCompleto() + "\n"
                        + "*Número:" + this.atencion.getNumero() + "\n"
                        + "*Fecha:" + fechaSolicitud + "\n" + "*Hora Solicitado:" + horaSolicitud + "\n"
                        + "*Nombre del Sector:" + (this.atencion.getSector().getNomSector()) + "\n _____________________";

                txtDescripcion.setText(info);
            }
        }
    }

//------------------------------------------------------------------------------
}
