/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.monitor;

import Controlador.ControladorMonitorTrabajador;
import Controlador.Interfaces.VistaMonitorTrabajador;
import Modelo.Datos.Puesto;
import Modelo.Datos.Sector;
import Modelo.Datos.Trabajador;
import Vista.atencion.AtencionTrabajador;

import java.util.List;

/**
 * @author Denise
 */
public class MonitorTrabajador extends javax.swing.JFrame implements VistaMonitorTrabajador {

    private ControladorMonitorTrabajador controlador;
    private Trabajador trabajador;

    public Trabajador getTrabajador() {
        return trabajador;
    }

    public void setTrabajador(Trabajador t) {
        this.trabajador = t;
    }

    public ControladorMonitorTrabajador getControlador() {
        return controlador;
    }

    public void setControlador(ControladorMonitorTrabajador controlador) {
        this.controlador = controlador;
    }

    public MonitorTrabajador(Trabajador t) {
        initComponents();
        this.cargarEtiqueta(t);
        this.setTrabajador(t);
        controlador = new ControladorMonitorTrabajador(this);
        controlador.obtenerPuestosLibres(t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPuestos = new javax.swing.JList();
        lblArea = new javax.swing.JLabel();
        lblSector = new javax.swing.JLabel();
        lblTrabajador = new javax.swing.JLabel();
        btnAsignarPuesto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Área:");

        jLabel3.setText("Sector:");

        jLabel4.setText("Trabajador:");

        jScrollPane1.setViewportView(lstPuestos);

        lblArea.setText("jLabel1");

        lblSector.setText("jLabel1");

        lblTrabajador.setText("jLabel1");

        btnAsignarPuesto.setText("Asignar Puesto");
        btnAsignarPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarPuestoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("PUESTOS DISPONIBLES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnAsignarPuesto))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4))
                                                .addGap(26, 26, 26)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblTrabajador)
                                                        .addComponent(lblSector)
                                                        .addComponent(lblArea))))
                                .addContainerGap(101, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(lblArea))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(lblSector))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(lblTrabajador))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAsignarPuesto))
                                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAsignarPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarPuestoActionPerformed
        asignarTrabajadorAPuesto();
    }//GEN-LAST:event_btnAsignarPuestoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarPuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblSector;
    private javax.swing.JLabel lblTrabajador;
    private javax.swing.JList lstPuestos;
    // End of variables declaration//GEN-END:variables

    private void cargarEtiqueta(Trabajador t) {
        this.lblArea.setText(t.getSectorTrabajador().getArea().getNomArea());
        this.lblSector.setText(t.getSectorTrabajador().getNomSector());
        this.lblTrabajador.setText(t.getNombreCompleto().toUpperCase());
    }

    @Override
    public void actualizarPuestos(List<Puesto> puestos) {
        lstPuestos.setListData(puestos.toArray());
    }

    private void asignarTrabajadorAPuesto() {
        Puesto miPuesto = (Puesto) lstPuestos.getSelectedValue();
        controlador.asignarTrabajadorAPuesto(miPuesto, trabajador);
    }

    @Override
    public void abrirAtencionTrabajador(Trabajador t) {
        dispose();
        new AtencionTrabajador(t).setVisible(true);
    }
}
