/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.monitor;

import Controlador.ControladorMonitorNumeros;
import Controlador.Interfaces.VistaMonitorNumeros;
import Modelo.Datos.Area;
import Modelo.Datos.Atencion;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Denise
 */
public class MonitorNumeros extends javax.swing.JFrame implements VistaMonitorNumeros{
    
    private ControladorMonitorNumeros controlador;
    
    public ControladorMonitorNumeros getControlador() {
        return controlador;
    }

    public void setControlador(ControladorMonitorNumeros controlador) {
        this.controlador = controlador;
    }

    public MonitorNumeros(Area area, int lineas) {
        initComponents();
        controlador = new ControladorMonitorNumeros(this);
        inicializarTabla(lineas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("AREA COMERCIAL");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualizar(String sector, String nro, String cliente, String puesto) {
        DefaultTableModel model = (DefaultTableModel)this.jTable1.getModel();
        model.removeRow(model.getRowCount()-1);
        Object[] f = new Object[]{
            sector, nro, cliente, puesto
        };
        model.insertRow(0, f);
    }

    private void inicializarTabla(int lineas){//recibo cant de numero ingresado en pantalla anterior
        DefaultTableModel model = (DefaultTableModel)this.jTable1.getModel();
        model.setNumRows(lineas);
        String[] titCol = new String[]{
            "Sector", "Numero", "Nombre Cliente", "Nro Puesto"
        };
        model.setColumnIdentifiers(titCol);
    }


}
